apiVersion: v1
kind: Pod
data: 
  mosquitto.conf: |
    log_dest stdout
    log_type all
    log_timestamp true
metadata: 
  name: nginx 
  labels: 
    app: nginx
spec: 
  containers: 
  - name: nginx-container 
    image: nginx 
    ports: 
    - containerPort: 80
    volumeMounts: 
    - name: nginx-vol
      mountPath: /usr/nginx/html
  - name: sidebar-container 
    image: some-image/curl 
    command: ["/bin/sh"]
    args: ["-c", "echo Hello"]

